### ISSUE TITLE
CheckList: Switching wormhole production to use wormhole-pro repo

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/wormhole-ui#26]
- [x] Pre requirement issues need to fixed
  - [x] https://github.com/darwinia-network/wormhole-pro/issues/20
  - [x] https://github.com/darwinia-network/wormhole-pro/issues/25
  - [x] https://github.com/darwinia-network/wormhole-pro/issues/24
- [x] Deployment
  - [x] Rename https://github.com/darwinia-network/wormhole to legacy-wormhole-ui
  - [x] Rename this repo to wormhole-ui
  - [x] Redeploy original legacy-wormhole-ui to https://legacy-wormhole.darwinia.network/
  - [x] Deploy this repo's latest release to replace production https://wormhole.darwinia.network/

**Comment by WoeOm** [comment]
https://github.com/darwinia-network/legacy-wormhole-ui

Has been renamed. 

> @WoeOm Rename https://github.com/darwinia-network/wormhole to legacy-wormhole-ui
> 
> @yunzck8s Redeploy original deprecated-wormhole-ui to https://legacy-wormhole.darwinia.network/
> Deploy this repo's latest release to replace production https://wormhole.darwinia.network/
> 
> thx to fix these

**Comment by HackFisher** [comment]
- [ ] Token Management and ERC20 should not be show in production pre-test env: https://github.com/darwinia-network/wormhole-ui/issues/28
- [ ] Features and bridges still in testing should be disabled/hidden in production & production test.
- [ ] Other checking and tests for production test @1022ranji 
- [ ] Confirm who should be responsible for the devops of this this repo @1022ranji @wi1dcard @yunzck8s @fewensa

**Comment by wi1dcard** [comment]
> * [ ]  Confirm who should be responsible for the devops of this repo @1022ranji @wi1dcard @yunzck8s @fewensa

Should be @fewensa. Currently we are migrating all the public frontend projects onto Vercel. Yalin is taking care of this. So as on, all the CI/CD and releasing cycle of public frontend projects in the future (including the new darwinia official website I saw created in the last few days), will be mainly managed by Yalin.

However, the old wormhole still uses the deprecated k8s CI/CD pipeline, therefore, replace the domain to legacy-wormhole.darwinia.network should be handled by me or @yunzck8s . In order to help Chen Zhao learning, I will follow up on this and make sure that he can solve this.

**Comment by wi1dcard** [comment]
Update from @fewensa, since the legacy wormhole will be still maintained in quite a while, it is decided to keep the legacy wormhole under wormhole.darwinia.network and Yalin is going to migrate the legacy wormhole onto Vercel. So this task won't require @yunzck8s anymore.
